---
title: "class_04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

full_data <- read_csv("data/full_data.csv")


target <- c ("Rachel Green", "Ross Geller", "Joey Tribbiani", "Chandler Bing", "Monica Geller", "Phoebe Buffay")

fulldata_main <- full_data%>%
  filter(speaker %in% target)%>%
  drop_na()

```

## Class Assessment (Where are you in your R journey?)

These are meant to help you asssess where you are in your R journey. If you can answer both of these questions without help, then you are a in a great place for the exam next week. If you struggle with these, practice some more. 

```{r}
ggplot(data = midwest, mapping = aes(x = poptotal))+
  geom_histogram(bins = 100)+
  annotate("text", x = 4500000, y = 25, label = "Which County Is This?")+
  labs(title = "Histogram of Midwestern Counties By Population", 
       x = "Population", y = "Number of Counties")
```


```{r}
ages <- tribble(
  ~speaker,      ~age,
  "Rachel",         23,
  "Phoebe",         28,
  "Ross",           31,
  "Monica",         24,
  "Chandler",       24,
  "Joey",           26
)

c_avg <- mean(ages$age)

ggplot(data = ages) +
  geom_bar(mapping = aes(x = speaker, 
                         y = age, 
                         fill = speaker), 
           stat = "identity")+
  geom_hline(aes(yintercept = c_avg))+
  labs(title = "How old were the Friends characters?", 
       x = "Character", y = "Age (in years)")+
  guides(fill=FALSE)
```


```{r create bar graph}
#default stat transformation fro geom_bar() is stat_count()
ggplot(data = full_data_new)+
  geom_bar(mapping = aes(x = speaker))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

# no stat transformation        
ages <- tribble(
  ~speaker,      ~age,
  "Rachel",         23,
  "Phoebe",         28,
  "Ross",           31,
  "Monica",         24,
  "Chandler",       24,
  "Joey",           26
)

c_avg <- mean(ages$age)

ggplot(data = ages) +
  geom_bar(mapping = aes(x = speaker, 
                         y = age, 
                         fill = speaker), 
           stat = "identity")+
  geom_hline(aes(yintercept = c_avg))+
  labs(title = "How old were the Friends characters?", 
       x = "Character", y = "Age (in years)")+
  guides(fill=FALSE)


```

## EDA

```{r}
full_data <- read_csv("data/full_data.csv")


target <- c ("Rachel Green", "Ross Geller", "Joey Tribbiani", "Chandler Bing", "Monica Geller", "Phoebe Buffay")

fulldata_main <- full_data%>%
  filter(speaker %in% target)%>%
  drop_na()

ggplot(data = fulldata_main, mapping = aes(x = emotion, fill = speaker)) +
  geom_bar()

ggplot(data = fulldata_main, 
       mapping = aes(x = emotion, y = stat(prop), 
                     group = 1, fill = speaker))+
  geom_bar()+
  facet_wrap(~speaker)+
  coord_flip()

ggplot(data = fulldata_main, 
       mapping = aes(x = speaker, y = stat(prop), 
                     group = 1, fill = emotion))+
  geom_bar()+
  facet_wrap(~emotion)+
  coord_flip()

select_emotions <- c("Sad","Mad","Scared")

fulldata_main%>%
  filter(emotion%in%select_emotions)%>%
  ggplot(mapping = aes(x = speaker, y = stat(prop), 
                       group = 1, fill = emotion))+
  geom_bar()+
  facet_wrap(~emotion)+
  guides(fill = FALSE)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```
## Data Transformations with dplyr
```{r}
target <- c ("Rachel Green", "Ross Geller", "Joey Tribbiani", "Chandler Bing", "Monica Geller", "Phoebe Buffay")
full_data_new <- filter(full_data, speaker %in% target)
full_data_new_na <- drop_na(full_data_new)

emotion_by_speaker <- full_data_new_na %>%
  group_by(speaker,emotion)%>%
  summarize(N=n())%>%
  mutate(freq = N / sum(N), pct = round((freq*100),1))

speaker_by_emotion <- full_data_new_na %>%
  group_by(emotion,speaker)%>%
  summarize(N=n())%>%
  mutate(freq = N / sum(N), pct = round((freq*100),1))
```

##Organ Donor EDA
```{r}
library(socviz)

organdata

by_country <- organdata %>%
  group_by(world, country, donors) %>%
  summarize_if(is.numeric,
               list(~ mean(., na.rm = TRUE),
                    ~ sd(., na.rm = TRUE))) %>%
  ungroup()
by_country

d <- ggplot(data = by_country,
            mapping = aes(x = roads_mean,
                          y = donors, color = world))
d + geom_point() +
  scale_x_log10() + scale_y_continuous(breaks = c(5, 15, 25),
                                       labels = c("Five", "Fifteen", "Twenty Five"))

e <- ggplot(data = by_country, mapping = aes(x = roads_mean, y = donors, color = world))
e + geom_point() + scale_color_discrete(labels = c("Corporatist", "Liberal","Social Democratic", "Unclassified")) +
  labs(x = "Road Deaths", y = "Donor Procurement",color = "Welfare State")+
  guides(color = FALSE)

```

